# app.py
"""
TotalVirus - simplified Flask backend (app.py)
Serves index.html (dark sci-fi UI) and provides API endpoints:
- POST /scan     -> returns { threat_score, reasons, sim_id, session_id }
- GET  /simulate/<sim_id> -> safe post-click sandbox (generated by backend)
- POST /log_sim  -> logs simulation interaction
- GET  /dashboard -> simple JSON viewer or HTML page
- GET  /api/logs -> returns recent logged interactions (JSON)

Run:
    python app.py

Requirements:
    pip install Flask
"""
from flask import Flask, request, jsonify, render_template, render_template_string
import sqlite3, os, uuid, json, re
from datetime import datetime

APP = Flask(__name__, template_folder="templates")
DB = "totalvirus_logs.db"

# ------------------ DB helpers ------------------
def init_db():
    if not os.path.exists(DB):
        conn = sqlite3.connect(DB)
        c = conn.cursor()
        c.execute('''
            CREATE TABLE interactions(
                id TEXT PRIMARY KEY,
                session_id TEXT,
                timestamp TEXT,
                input_type TEXT,
                raw_input TEXT,
                threat_score REAL,
                reasons TEXT,
                simulated_click INTEGER,
                entered_credentials INTEGER,
                training_shown INTEGER
            )
        ''')
        conn.commit()
        conn.close()

def log_interaction(rec):
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    c.execute('''
        INSERT INTO interactions(id, session_id, timestamp, input_type, raw_input, threat_score, reasons, simulated_click, entered_credentials, training_shown)
        VALUES (?,?,?,?,?,?,?,?,?,?)
    ''', (rec['id'], rec['session_id'], rec['timestamp'], rec['input_type'], rec['raw_input'], rec['threat_score'], json.dumps(rec['reasons']), rec['simulated_click'], rec['entered_credentials'], rec['training_shown']))
    conn.commit()
    conn.close()

# ------------------ Heuristics ------------------
SUSPICIOUS_TLDS = ['.xyz', '.top', '.icu', '.club', '.online', '.pw']
SHORTENERS = ['bit.ly','t.co','tinyurl.com','goo.gl','ow.ly','is.gd']
URGENT_WORDS = ['urgent','immediately','verify','confirm','act now','suspend','limited','winner','congrat']

def analyze_text_input(text):
    t = (text or "").lower()
    reasons = []
    score = 0

    # urgent words
    found = [w for w in URGENT_WORDS if w in t]
    if found:
        reasons.append("Urgency/pressure language: " + ", ".join(found))
        score += 25

    # IP in URL
    if re.search(r'://\d+\.\d+\.\d+\.\d+', text or ""):
        reasons.append("Contains raw IP in URL")
        score += 20

    # domain heuristics
    for d in re.findall(r'https?://([^/\s]+)', text or ""):
        if len(d.split('.')) >= 4:
            reasons.append(f"Deep subdomain: {d}")
            score += 8
        for s in SHORTENERS:
            if s in d:
                reasons.append(f"URL shortener: {s} (obscures destination)")
                score += 12
        for tld in SUSPICIOUS_TLDS:
            if d.endswith(tld):
                reasons.append(f"Suspicious TLD: {tld} in {d}")
                score += 6
        if re.search(r'(login|secure|account|verify|update)[\W\-_]*[a-z0-9]*\.', d):
            reasons.append(f"Deceptive token in domain: {d}")
            score += 8

    # attachments/base64 mentions
    if 'attachment' in t or 'base64' in t:
        reasons.append("Mentions attachment/base64 — attachments can be risky")
        score += 6

    # generic greeting
    if 'dear user' in t or 'dear customer' in t:
        reasons.append("Generic greeting (not personalized)")
        score += 4

    if score == 0:
        reasons.append("No obvious heuristic matches (low confidence)")

    if score > 100:
        score = 100

    return round(score,1), reasons

# ------------------ Routes ------------------
@APP.route("/")
def index():
    return render_template("index.html")

@APP.route("/scan", methods=["POST"])
def scan():
    data = request.get_json() or {}
    text = data.get("input","")
    session_id = data.get("session_id", uuid.uuid4().hex[:8])
    score, reasons = analyze_text_input(text)
    # create sim id
    sim_id = uuid.uuid4().hex[:8]
    # log initial record
    rec = {
        "id": uuid.uuid4().hex,
        "session_id": session_id,
        "timestamp": datetime.utcnow().isoformat(),
        "input_type": "text",
        "raw_input": (text or "")[:1000],
        "threat_score": score,
        "reasons": reasons,
        "simulated_click": 0,
        "entered_credentials": 0,
        "training_shown": 0
    }
    log_interaction(rec)
    return jsonify({"threat_score": score, "reasons": reasons, "sim_id": sim_id, "session_id": session_id})

# safe simulation (post-click sandbox)
SIM_TEMPLATE = """
<!doctype html>
<html>
<head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Simulation</title>
<style>body{background:#040612;color:#dfffe8;font-family:Arial;padding:20px}.card{max-width:600px;margin:22px auto;background:#07121a;padding:18px;border-radius:10px}input{width:100%;padding:10px;margin-top:8px;border-radius:6px;border:1px solid #1a2a30;background:#011219;color:#dfffe8}button{margin-top:10px;padding:10px;border-radius:8px;border:none;background:#00d0a0;color:#031219}</style>
</head>
<body>
<div class="card">
  <h2>Safe Post‑Click Simulation</h2>
  <p style="color:#a7d9cf">This sandbox will NOT store raw credentials. It's used to measure susceptibility only.</p>
  <form id="f">
    <label>Username or email</label>
    <input id="u" placeholder="you@example.com">
    <label>Password</label>
    <input id="p" type="password" placeholder="password">
    <button type="submit">Submit</button>
  </form>
  <div id="msg" style="margin-top:12px"></div>
</div>
<script>
const simId = "{{sim_id}}";
const sess = "{{session_id}}";
document.getElementById('f').addEventListener('submit', async e=>{
  e.preventDefault();
  const u = document.getElementById('u').value;
  const p = document.getElementById('p').value;
  // send only presence flags to backend for safety
  const payload = { sim_id: simId, session_id: sess, entered_username: u?1:0, entered_password: p?1:0 };
  const r = await fetch('/log_sim', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify(payload)});
  const j = await r.json();
  document.getElementById('msg').innerHTML = '<div style="color:#bfffe6">'+j.message+'</div>';
  setTimeout(()=> location.href='/training?session='+sess, 900);
});
</script>
</body>
</html>
"""

@APP.route("/simulate/<sim_id>")
def simulate(sim_id):
    session = request.args.get("session", "local")
    return render_template_string(SIM_TEMPLATE, sim_id=sim_id, session_id=session)

@APP.route("/log_sim", methods=["POST"])
def log_sim():
    data = request.get_json() or {}
    session_id = data.get("session_id", "anon")
    entered_username = int(data.get("entered_username", 0))
    entered_password = int(data.get("entered_password", 0))
    rec = {
        "id": uuid.uuid4().hex,
        "session_id": session_id,
        "timestamp": datetime.utcnow().isoformat(),
        "input_type": "simulation",
        "raw_input": data.get("sim_id","(sim)"),
        "threat_score": 0.0,
        "reasons": ["simulation result"],
        "simulated_click": 1,
        "entered_credentials": 1 if (entered_username or entered_password) else 0,
        "training_shown": 1
    }
    log_interaction(rec)
    return jsonify({"ok": True, "message": "Simulation logged. Redirecting to micro-training..."})

TRAIN_HTML = """
<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Training</title>
<style>body{background:#03121a;color:#e6fff6;font-family:Arial;padding:20px}.card{max-width:760px;margin:18px auto;background:#051a23;padding:18px;border-radius:10px}button{padding:10px;border-radius:8px;border:none;margin-top:8px}</style>
</head><body>
<div class="card">
  <h2>Micro-Training</h2>
  <p>Quick tips:</p>
  <ul>
    <li>Hover links to see destination before clicking.</li>
    <li>Check sender's full email address — display name may be spoofed.</li>
    <li>When in doubt, open the service manually (don't follow links).</li>
  </ul>
  <h3>Mini Quiz</h3>
  <p>Q: If an email links to <em>https://account-secure.paypal.login.xzy</em>, what's the safest action?</p>
  <button onclick="feedback(2)">A) Click and login</button>
  <button onclick="feedback(1)">B) Hover and then go to official site manually</button>
  <div id="fb" style="margin-top:12px"></div>
</div>
<script>
function feedback(n){
  const fb = document.getElementById('fb');
  if(n===1) fb.innerHTML='<div style="color:#bfffe6">Good — open official site manually.</div>';
  else fb.innerHTML='<div style="color:#ffb3b3">Not safe — do not click suspicious links.</div>';
}
</script>
</body></html>
"""

@APP.route("/training")
def training():
    return TRAIN_HTML

@APP.route("/api/logs")
def api_logs():
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    rows = c.execute("SELECT timestamp,session_id,input_type,threat_score,simulated_click,entered_credentials,reasons FROM interactions ORDER BY timestamp DESC LIMIT 200").fetchall()
    conn.close()
    out = []
    for r in rows:
        out.append({
            "timestamp": r[0],
            "session_id": r[1],
            "input_type": r[2],
            "threat_score": r[3],
            "simulated_click": r[4],
            "entered_credentials": r[5],
            "reasons": json.loads(r[6]) if isinstance(r[6], str) else r[6]
        })
    return jsonify({"rows": out})

# optional simple HTML dashboard
DASH_HTML = """
<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dashboard</title>
<style>body{background:#021018;color:#bfece3;font-family:Arial;padding:18px}table{width:100%;border-collapse:collapse}td,th{padding:8px;border-bottom:1px solid rgba(255,255,255,0.06)}</style>
</head><body>
<h2>Local Dashboard</h2>
<div id="tbl">Loading...</div>
<script>
fetch('/api/logs').then(r=>r.json()).then(j=>{
  const el = document.getElementById('tbl');
  if(!j.rows.length) { el.innerHTML='<i>No logs yet.</i>'; return; }
  let html = '<table><tr><th>Time</th><th>Session</th><th>Type</th><th>Score</th><th>Sim</th><th>Creds</th><th>Reasons</th></tr>';
  j.rows.forEach(r => {
    html += `<tr><td>${r.timestamp}</td><td>${r.session_id}</td><td>${r.input_type}</td><td>${r.threat_score}</td><td>${r.simulated_click}</td><td>${r.entered_credentials}</td><td>${JSON.stringify(r.reasons).slice(0,120)}</td></tr>`;
  });
  html += '</table>';
  el.innerHTML = html;
});
</script>
</body></html>
"""

@APP.route("/dashboard")
def dashboard():
    return DASH_HTML

# ------------------ Start ------------------
if __name__ == "__main__":
    init_db()
    APP.run(host="0.0.0.0", port=5000, debug=True)
